<a href="https://colab.research.google.com/github/DanielRomeo/machinelearningscripts/blob/main/00_pytorch_fundermentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Pytorch Fundermentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to tensors

* Tensors are created with `torch.Tensor()`



In [4]:
#scalars: creating a scalar:
scalar = torch.tensor(7);
scalar

tensor(7)

In [7]:
# how many dimentions?
scalar.ndim

0

In [6]:
# Get tensor back as python int:
scalar.int()

tensor(7, dtype=torch.int32)

Vector

In [8]:
# Create a vector and display it:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [16]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [18]:
# TENSOR
TENSOR  = torch.tensor([[[1,2,3],
                         [3,6,9],
                         [2,4,5]]])
# print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape) # one array originally, then second one, has 3 items in it,
# thirdly, it has 3 elements each.

3
torch.Size([1, 3, 3])


In [33]:
# Practicing tensors:
MYTENSOR = torch.tensor([[[[], []]], [[[], []]]])
MYTENSOR.shape

torch.Size([2, 1, 2, 0])

# Random tensors
Why random tensors?
because they nn start with random numbers and ajust those numbers to better represent the data.


In [40]:
# Create a random tensor or size (3,4)
random_tensor = torch.rand(3,4)
print(random_tensor)
print("dimentions of random tensor is: ", random_tensor.ndim)

tensor([[0.0173, 0.9034, 0.5313, 0.0946],
        [0.5749, 0.4311, 0.5734, 0.1138],
        [0.0096, 0.8052, 0.3256, 0.5996]])
dimentions of random tensor is:  2
